"""Typed, layered configuration for WeCoder.AI."""

from __future__ import annotations

import os
import tomllib
from collections.abc import Mapping
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path

from wecoder.errors import ConfigError

# Environment variables use this prefix: ``WECODER_<SECTION>_<KEY>``.
ENV_PREFIX = "WECODER_"

# Maps a WECODER_* suffix to the (section, key) it overrides.  The table is
# explicit so a multi-word key (e.g. ``max_turns``) is never ambiguous.
_ENV_KEY_TARGETS: dict[str, tuple[str, str]] = {
    "PROJECT_WORKSPACE": ("project", "workspace"),
    "MODEL_PROVIDER": ("model", "provider"),
    "MODEL_MODEL": ("model", "model"),
    "MODEL_BASE_URL": ("model", "base_url"),
    "MODEL_API_KEY_ENV": ("model", "api_key_env"),
    "LIMITS_MAX_TURNS": ("limits", "max_turns"),
    "LIMITS_MAX_TOKENS": ("limits", "max_tokens"),
    "LOGGING_LEVEL": ("logging", "level"),
}

# Canonical defaults.  This dict is the single schema description: sections,
# keys, and default values.  TOML files and environment variables may override
# these leaves.
_DEFAULTS: dict[str, dict[str, object]] = {
    "project": {"workspace": "."},
    "model": {
        "provider": "ollama",
        "model": "qwen2.5-coder",
        "base_url": "",
        "api_key_env": "OPENAI_API_KEY",
    },
    "limits": {"max_turns": 20, "max_tokens": 100000},
    "logging": {"level": "INFO"},
}

# Field names containing these markers are treated as sensitive by
# :meth:`Settings.redacted` and never printed in full.
_SENSITIVE_NAME_MARKERS = ("key", "token", "secret", "password")

# Template written by ``wecoder init``.  It contains only defaults and
# comments — never secrets.
DEFAULT_CONFIG_TEXT = """\
# WeCoder.AI project configuration.
# Generated by `wecoder init`. It contains no secrets and is safe to commit.

[project]
# Workspace root for a session. Stored as a string; resolved in a later phase.
workspace = "."

[model]
# Model provider. Unused until Phase 02. Example values: "ollama", "openai_compat".
provider = "ollama"
model = "qwen2.5-coder"
# Empty string means "provider default".
base_url = ""
# Name of the environment variable that holds the API key (never the key itself).
api_key_env = "OPENAI_API_KEY"

[limits]
max_turns = 20
max_tokens = 100000

[logging]
level = "INFO"
"""


@dataclass(frozen=True)
class ProjectSettings:
    """Workspace / project configuration."""

    workspace: str = "."


@dataclass(frozen=True)
class ModelSettings:
    """Model selection.  Not consumed by any code until Phase 02."""

    provider: str = "ollama"
    model: str = "qwen2.5-coder"
    base_url: str = ""
    api_key_env: str = "OPENAI_API_KEY"


@dataclass(frozen=True)
class LimitsSettings:
    """Session budget limits."""

    max_turns: int = 20
    max_tokens: int = 100000


@dataclass(frozen=True)
class LoggingSettings:
    """Logging configuration."""

    level: str = "INFO"


@dataclass(frozen=True)
class Settings:
    """Frozen, fully-resolved configuration.

    Constructed by :meth:`Settings.load`, which applies the documented
    precedence.  ``config_paths`` records which files were actually found
    (in load order) so the CLI can report them.
    """

    project: ProjectSettings
    model: ModelSettings
    limits: LimitsSettings
    logging: LoggingSettings
    config_paths: tuple[Path, ...] = ()

    @classmethod
    def load(
        cls,
        *,
        cwd: str | Path | None = None,
        home: str | Path | None = None,
        env: Mapping[str, str] | None = None,
    ) -> Settings:
        """Resolve settings from defaults, files, and environment.

        ``cwd``/``home`` override the process defaults so callers and tests
        can point at isolated directories.  ``env`` overrides ``os.environ``
        so tests can inject a controlled environment.
        """
        cwd = Path(cwd) if cwd is not None else Path.cwd()
        home = Path(home) if home is not None else Path.home()
        env_vars = dict(os.environ) if env is None else dict(env)

        merged = deepcopy(_DEFAULTS)
        config_paths: list[Path] = []

        user_path = home / ".wecoder" / "config.toml"
        project_path = cwd / ".wecoder" / "config.toml"

        for path in (user_path, project_path):
            if path.is_file():
                _merge_toml(merged, path)
                config_paths.append(path)

        _apply_env(merged, env_vars)

        return cls(
            project=ProjectSettings(
                workspace=_require_str(merged["project"]["workspace"], "project.workspace"),
            ),
            model=ModelSettings(
                provider=_require_str(merged["model"]["provider"], "model.provider"),
                model=_require_str(merged["model"]["model"], "model.model"),
                base_url=_require_str(merged["model"]["base_url"], "model.base_url"),
                api_key_env=_require_str(
                    merged["model"]["api_key_env"], "model.api_key_env"
                ),
            ),
            limits=LimitsSettings(
                max_turns=_require_int(merged["limits"]["max_turns"], "limits.max_turns"),
                max_tokens=_require_int(
                    merged["limits"]["max_tokens"], "limits.max_tokens"
                ),
            ),
            logging=LoggingSettings(
                level=_require_str(merged["logging"]["level"], "logging.level"),
            ),
            config_paths=tuple(config_paths),
        )

    def redacted(self) -> dict[str, object]:
        """Return the settings as a nested dict with sensitive values masked.

        Any leaf whose field name looks like a key/token/secret/password is
        replaced with ``"***"``.  Safe to print or log.
        """
        return {
            "project": _scrub(self.project),
            "model": _scrub(self.model),
            "limits": _scrub(self.limits),
            "logging": _scrub(self.logging),
        }


def _scrub(obj: object) -> dict[str, object]:
    return {
        name: ("***" if _is_sensitive_name(name) else value)
        for name, value in vars(obj).items()
    }


def _is_sensitive_name(name: str) -> bool:
    lowered = name.lower()
    return any(marker in lowered for marker in _SENSITIVE_NAME_MARKERS)


def _merge_toml(merged: dict[str, dict[str, object]], path: Path) -> None:
    """Merge a TOML file into ``merged``, keeping only known keys."""
    try:
        with path.open("rb") as fh:
            data = tomllib.load(fh)
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ConfigError(f"invalid config file {path}: {exc}") from exc

    for section, keys in _DEFAULTS.items():
        section_data = data.get(section, {})
        if not isinstance(section_data, dict):
            raise ConfigError(
                f"config file {path}: section [{section}] must be a TOML table"
            )
        for key in keys:
            if key in section_data:
                merged[section][key] = section_data[key]


def _apply_env(
    merged: dict[str, dict[str, object]],
    env_vars: Mapping[str, str],
) -> None:
    """Apply WECODER_* environment variables over the merged settings."""
    for suffix, (section, key) in _ENV_KEY_TARGETS.items():
        env_name = ENV_PREFIX + suffix
        if env_name not in env_vars:
            continue
        raw = env_vars[env_name]
        default = _DEFAULTS[section][key]
        merged[section][key] = _coerce(raw, default)


def _require_str(value: object, name: str) -> str:
    if isinstance(value, str):
        return value
    raise ConfigError(f"config key {name} must be a string, got {type(value).__name__}")


def _require_int(value: object, name: str) -> int:
    if isinstance(value, int) and not isinstance(value, bool):
        return value
    raise ConfigError(f"config key {name} must be an integer, got {type(value).__name__}")


def _coerce(value: str, default: object) -> object:
    """Convert a string env value to the type of ``default``."""
    if isinstance(default, bool):
        return value.strip().lower() in ("1", "true", "yes", "on")
    if isinstance(default, int):
        return int(value)
    if isinstance(default, float):
        return float(value)
    return str(value)


__all__ = [
    "Settings",
    "ProjectSettings",
    "ModelSettings",
    "LimitsSettings",
    "LoggingSettings",
    "ENV_PREFIX",
    "DEFAULT_CONFIG_TEXT",
]
